#TO FIND SIMPLE INTEREST
P=float(input("ENTER PRINCIPAL AMOUNT:"))
R=float(input("ENTER RATE OF INTEREST:"))
T=float(input("ENTER TIME PERIOD:"))
SI=(P*R*T)/100
print("THE SIMPLE INTEREST IS:",SI)
